/** Allowed categories, as stored and returned by the API. Forms use `VOX_CATEGORIES_ALPHABETICAL`. */
export const VOX_CATEGORIES_ALL = [
  "General",
  "Voxer",
  "Anecdotas",
  "Consejos",
  "Fitness",
  "Preguntas",
  "Salud",
  "Arte",
  "Ciencia",
  "Religion",
  "Historia",
  "Literatura",
  "Lugares e idiomas",
  "Moda",
  "Comida",
  "Musica",
  "Anime/Manga",
  "Cine y TV",
  "Deportes",
  "Futbol",
  "Humor",
  "Videojuegos",
  "Redes",
  "Normies",
  "Omniverso3p",
  "Mujeres",
  "Economia",
  "Guerra",
  "Politica",
  "Noticias",
  "Tecnologia",
  "Programacion",
  "Inteligencia Artificial",
  "Gozadores",
  "Porno",
  "Gay",
  "Conspiraciones",
  "Paranormal",
  "Fetiches",
  "Hentai",
  "Random",
  "Videos",
  "Avatarfags",
  "Animales",
] as const;
export type VoxCategory = (typeof VOX_CATEGORIES_ALL)[number];
export const DEFAULT_VOX_CATEGORY: VoxCategory = "General";
export const VOX_CATEGORIES_ALPHABETICAL: readonly VoxCategory[] = [...VOX_CATEGORIES_ALL].sort(
  (a, b) => a.localeCompare(b, "es", { sensitivity: "base" }),
);
